version: "3.1"

services:
  db:
    image: postgres:latest
    volumes:
      - aidea-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aidea
    ports:
      - "5432:5432"

volumes:
  aidea-data:
